name: Build and Test

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.rs'
      - '.github/workflows/*'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.rs'
      - '.github/workflows/*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Cancel Workflow Action
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Get Latest Stable Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        components: clippy
    - name: Lint
      run: cargo clippy --all --all-features
    - name: Build
      run: cargo build --verbose --release --all --all-features && cargo bench --all --no-run
    - name: Run tests
      run: cargo test --verbose --release --all --all-features